config/routes.rb
PickupSports::Application.routes.draw do

  root "users#index"
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  match "/signup", to: "users#new", via: "get"
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :sessions, only: [:new, :create, :destroy]

  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: "delete"
  







  

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	
	# reason we dont need attr_accessibles? ---deprectaed_mass_assignment_security

	# https://github.com/rails/rails/blob/master/activemodel/lib/active_model/secure_password.rb
	has_secure_password # more info on this method in the link above

	validates :first_name, presence: true 
	validates :last_name, presence: true 

	VALID_PROFILE_NAME_REGEX = /\A[a-zA-Z0-9_-]+\z/
	validates :profile_name, presence: true, uniqueness: true, length: { maximum: 50 },
			                format: {
			                  with: VALID_PROFILE_NAME_REGEX,
			                  message: 'Must be formatted correctly.'
			                }
			                # \A # Beginning of a string (not a line!)
			                # \z # End of a string
			                # [...] # match anything within the brackets
			                # + # match the preceding element one or more times

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, uniqueness: { case_sensitive: false },
  							 format: { 
  								with: VALID_EMAIL_REGEX, 
			                  	message: 'Must be formatted correctly.'
			                   }
	validates :password, length: { minimum: 6 }

	def full_name
		first_name + " " + last_name
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # By default, all the helpers are available in the views but not in the controllers. 
  # We need the methods from the Sessions helper in both places, so we have to include it explicitly.
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			# redirect to users page
			sign_in user
			redirect_back_or(user_path(user))
		else
			flash.now[:error] = "Invalid email/password combination"
			render "new"
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :signed_in_user, only: [:edit, :update, :index, :destroy]
	before_action :correct_user, only: [:edit, :update]
	before_action :admin_user, only: :destroy

	def index
			@users = User.paginate(page: params[:page])
	end

	def new
		@user = User.new
	end

	def show
		@user = User.find_by(id: params[:id])
	end

	def create
		@user = User.new(user_params)

   	respond_to do |format|
			if @user.save
				format.html do
					flash[:notice] = "Welcome to the Sample App!"
					sign_in @user
		        	redirect_to users_path(@user)
		        end
			else
				format.html { render action: "new" }
			end
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
			redirect_to user_path(@user)
		else 
			flash.now[:error] = "Invalid Entry"
			render action: "edit"
		end
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User deleted."
		redirect_to users_path
	end

	private

		def user_params
			params.require(:user).permit(:first_name, :last_name, :profile_name,
											 :email, :password, :password_confirmation)
		end

		def signed_in_user
			unless signed_in?
				store_location
				redirect_to signin_path, notice: "Please sign in."
			end
		end

		def correct_user
			@user = User.find(params[:id])
			redirect_to root_url unless current_user?(@user)
		end

		def admin_user
			redirect_to(root_url) unless current_user.admin?
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

# By default, all the helpers are available in the views but not in the controllers. 

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		# permanent = { value: remember_token, expires: 20.years.from_now.utc }
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||=  User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end
	
	def signed_in?
		!current_user.nil?
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def redirect_back_or(default)
		# session is an rails helper
		# acts like a cookie varible that automatically expires upon browser close
		redirect_to(session[:return_to] || default) 
		session.delete(:return_to)
	end

	def store_location
		# save the wanted url if and only if the url request is a get request
		session[:return_to] = request.url if request.get?
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.haml
%header
  .navbar.navbar-fixed-top.inverse
    .navbar-inner
      .container
        = link_to "Pickup Golf", root_path, class: "brand"
        %nav
          %ul.nav.pull-right
            %li
              = link_to "Home", root_path
            - if signed_in?
              %li
                = link_to "Users", users_path
              %li.dropdown
                %a.dropdown-toggle{:href => "#", :data => {:toggle => "dropdown"}} 
                  Account 
                  %b.caret
                %ul.dropdown-menu
                  %li
                    = link_to "Profile", current_user
                  %li 
                    = link_to "Settings", edit_user_path(current_user)
                  %li.divider
                  %li
                    = link_to "Sign Out", signout_path, method: "delete"
            - else
              %li
                = link_to "Sign In", signin_path
              %li
                = link_to "Sign Up", signup_path

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
	%head
		%title Pickup Sports
		= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
		= javascript_include_tag "application", "data-turbolinks-track" => true 
		= csrf_meta_tags
	%body
		= render 'layouts/header'
		.container
			- flash.each do |key, value|
				.alert{:class => "alert-#{key}"}= value

			= yield

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2.alert.alert-error= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name, "First Name"
    = f.text_field :first_name
  .field
    = f.label :last_name, "Last Name"
    = f.text_field :last_name
  .field
    = f.label :profile_name, "Profile Name"
    = f.text_field :profile_name
  .field
    = f.label :email
    = f.text_field :email, type: "email"
  .field
    = f.label :password
    = f.text_field :password, type: "password"
  .field
    = f.label :password_confirmation, "Confirmation"
    = f.text_field :password_confirmation, type: "password"

  .actions
    = f.submit 'Create my account'

app/views/users/edit.html.haml
%h1 Edit Your Info

= form_for(@user) do |f|
	- if @user.errors.any?
		#error_explanation
			%h2.alert.alert-error="#{pluralize(@user.errors.count, "error")} prohibited this user from being updated"
			%ul
				- @user.errors.full_messages.each do |msg|
					%li= msg
					
	.field
		= f.label :first_name, "First Name"
		= f.text_field :first_name
	.field
		= f.label :last_name, "Last Name"
		= f.text_field :last_name
	.field
		= f.label :profile_name, "Profile Name"
		= f.text_field :profile_name
	.field
		= f.label :email
		= f.text_field :email, type: "email"
	%br
	.field
		= f.label :password, "Password"
		= f.text_field :password, type: "password"
	.field
		= f.label :password_confirmation, "Confirmation"
		= f.text_field :password_confirmation, type: "password"

	.action 
		= f.submit "Update Info"

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 All users

= will_paginate

- @users.each do |user|
	%tr
		%td= link_to user.full_name, user_path(user)
		%td= link_to 'Show', user
		%td= link_to 'Edit', edit_user_path(user)
		- if current_user.admin? && !current_user?(user)
			%td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

	%br
	%br

= link_to 'New User', new_user_path

= will_paginate

app/views/users/new.html.haml
%h1 Sign Up

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%h1= @user.full_name

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path

/ %strong{:class => "code", :id => "message"} Hello, World!
/ %strong.code#message Hello, World!

/ <div class='item' id='item<%= item.id %>'>
/   <%= item.body %>
/ </div>
/ .item{:id => "item#{item.id}"}= item.body